name: Deploy Backend (NestJS EC2)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e
            cd ${{ secrets.APP_DIR }}
            git pull origin main
            npm install
            npm run build
            pm2 reload ecosystem.config.js || pm2 start ecosystem.config.js
            pm2 save
